line-length = 120

[lint]
select = [
    "A", # flake8-builtins
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "SIM", # flake8-simplify
    "S", # flake8-bandit
    "D", "E", "W", # pydocstyle
    "F", # pyflakes
    "I", # isort
    "RUF", # specific ruff rules
]
ignore = [
    "D107", # missing docstring in classes `__init__`
    "D104", # missing docstring in packages `__init__`
    "D100", # missing docstring in modules `__init__`
]

[lint.per-file-ignores]
# Tests don't require rigorous docstrings. Ignore the S101 (assert detected) rule.
"*tests/*" = ["D", "S101"]
"*testing/*" = ["D", "S101"]

[lint.pydocstyle]
convention = "google"

[lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder" ]
known-local-folder = ["tests"]
